name = "scs-market-place"
account_id = "YOUR_ACCOUNT_ID_HERE"
compatibility_date = "2026-02-07"
pages_build_output_dir = "./dist"

[vars]
SITE_TITLE = "Simply Complex Solutions"
SITE_DESCRIPTION = "Premium Automation Upgrades"
